# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  testResults: 

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


- task: CmdLine@2
  displayName: Install Newman
  inputs:
    script: 'sudo npm install -g newman'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: CmdLine@2
  inputs:
    script: 'echo ''$(System.DefaultWorkingDirectory)'''

- task: CmdLine@2
  displayName: Run Example Tests
  inputs:
    script: 'newman run PostmanTests.postman_collection.json -e PostmanTestEnv.postman_environment.json --reporters cli,junit --reporter-junit-export Results/junitReport.xml'
    workingDirectory: '$(System.DefaultWorkingDirectory)'



- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/Results/*.xml'